package io.talevia.core.tool.builtin.aigc

import io.talevia.core.AssetId
import io.talevia.core.JsonConfig
import io.talevia.core.SourceNodeId
import io.talevia.core.bus.BusEvent
import io.talevia.core.cost.AigcPricing
import io.talevia.core.domain.MediaAsset
import io.talevia.core.domain.MediaMetadata
import io.talevia.core.domain.ProjectStore
import io.talevia.core.domain.Resolution
import io.talevia.core.domain.source.consistency.FoldedPrompt
import io.talevia.core.platform.BundleBlobWriter
import io.talevia.core.platform.ImageGenEngine
import io.talevia.core.platform.ImageGenRequest
import io.talevia.core.tool.ToolApplicability
import io.talevia.core.tool.ToolContext
import io.talevia.core.tool.ToolResult
import kotlinx.datetime.Clock
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.jsonObject
import kotlinx.serialization.serializer
import kotlin.time.Duration
import kotlin.uuid.ExperimentalUuidApi
import kotlin.uuid.Uuid

/**
 * Generate an image via an [ImageGenEngine], persist the bytes into the project
 * bundle via a [BundleBlobWriter], append the resulting [MediaAsset] to
 * `Project.assets`, and surface a [AssetId] that downstream tools (e.g.
 * `add_clip`) can use.
 *
 * The bundle layout means generated bytes live at
 * `<bundleRoot>/media/<assetId>.png` and travel with the project — git push /
 * `cp -R` ships generated images alongside the project DAG, so collaborators
 * see the same artefacts without re-billing the provider.
 *
 * Seed + provenance handling (VISION §3.1): delegates to [AigcPipeline] so this tool
 * and every future AIGC tool share one implementation of "mint a seed if missing,
 * record the full generation parameters."
 *
 * Lockfile cache (VISION §3.1 "产物可 pin"): before calling the engine the tool
 * hashes `(tool id, effective prompt, model, seed, dimensions, bindings, negative,
 * referenceAssetIds, loraPins)` and looks the hash up in [Project.lockfile]. On a
 * hit it returns the cached asset without re-calling the provider — bit-identical
 * reuse for the common "same inputs, different turn" case. On a miss it generates,
 * persists, and appends a new entry. Every axis the engine *could* vary on must
 * be hashed, otherwise semantically distinct generations would collide on the key.
 *
 * Consistency bindings (VISION §3.3): see [AigcPipeline.foldPrompt] — identical
 * behavior to the previous implementation.
 *
 * Permission: `"aigc.generate"` — defaults to ASK via
 * [io.talevia.core.permission.DefaultPermissionRuleset]; the server maps
 * ASK to deny, which is the correct headless default.
 *
 * Project binding required: the tool resolves [Input.projectId] (or falls
 * back to [ToolContext.currentProjectId]) and writes into that bundle. A
 * dispatch with no project binding fails loud — consistent with the
 * [ToolApplicability.RequiresProjectBinding] gate.
 */
class GenerateImageTool(
    override val engine: ImageGenEngine,
    internal val bundleBlobWriter: BundleBlobWriter,
    internal val projectStore: ProjectStore,
) : ImageAigcGenerator {

    companion object {
        const val ID = "generate_image"
    }

    override suspend fun generateBatch(
        input: Input,
        ctx: ToolContext,
        variantCount: Int,
    ): List<ToolResult<Output>> = executeBatch(input, ctx, variantCount)

    @Serializable
    data class Input(
        val prompt: String,
        val model: String = "gpt-image-1",
        val width: Int = 1024,
        val height: Int = 1024,
        val seed: Long? = null,
        val projectId: String? = null,
        val consistencyBindingIds: List<String>? = null,
    )

    @Serializable
    data class Output(
        val assetId: String,
        val width: Int,
        val height: Int,
        val providerId: String,
        val modelId: String,
        val modelVersion: String?,
        val seed: Long,
        val parameters: JsonObject,
        val effectivePrompt: String,
        val appliedConsistencyBindingIds: List<String>,
        /** Merged negative prompt from bound style_bibles (null when no negatives were folded). */
        val negativePrompt: String? = null,
        /** Asset ids of reference images passed to the engine (empty when no character_ref supplied any). */
        val referenceAssetIds: List<String> = emptyList(),
        /** LoRA adapter ids that were pinned via bound character_refs (empty when none supplied one). */
        val loraAdapterIds: List<String> = emptyList(),
        /** True when this asset came from [Project.lockfile] rather than a fresh engine call. */
        val cacheHit: Boolean = false,
    )

    @OptIn(ExperimentalUuidApi::class)
    override suspend fun generate(input: Input, ctx: ToolContext): ToolResult<Output> {
        val pid = ctx.resolveProjectId(input.projectId)
        AigcBudgetGuard.enforce(ID, projectStore, pid, ctx)
        val seed = AigcPipeline.ensureSeed(input.seed)
        val folded = resolveConsistency(input, pid)

        val referenceAssetPaths = resolveReferenceAssetPaths(pid, folded.referenceAssetIds)
        val loraKey = folded.loraPins.joinToString(",") { "${it.adapterId}@${it.weight}" }

        val inputHash = AigcPipeline.inputHash(
            listOf(
                "tool" to ID,
                "model" to input.model,
                "w" to input.width.toString(),
                "h" to input.height.toString(),
                "seed" to seed.toString(),
                "prompt" to folded.effectivePrompt,
                "bindings" to folded.appliedNodeIds.joinToString(","),
                "neg" to (folded.negativePrompt ?: ""),
                "refs" to folded.referenceAssetIds.joinToString(","),
                "lora" to loraKey,
            ),
            variantIndex = ctx.variantIndex,
        )

        if (!ctx.isReplay) {
            val cached = AigcPipeline.findCached(projectStore, pid, inputHash)
            ctx.publishEvent(io.talevia.core.bus.BusEvent.AigcCacheProbe(toolId = ID, hit = cached != null))
            if (cached != null) {
                return hit(cached, folded, input)
            }
        }

        val result = AigcPipeline.withProgress(
            ctx = ctx,
            jobId = "gen-image-${inputHash.take(8)}",
            startMessage = "generating ${input.width}x${input.height} image with ${input.model}",
            toolId = ID,
            providerId = engine.providerId,
        ) {
            engine.generate(
                ImageGenRequest(
                    prompt = folded.effectivePrompt,
                    modelId = input.model,
                    width = input.width,
                    height = input.height,
                    seed = seed,
                    n = 1,
                    negativePrompt = folded.negativePrompt,
                    referenceAssetPaths = referenceAssetPaths,
                    loraPins = folded.loraPins,
                ),
                onWarmup = { phase ->
                    ctx.publishEvent(
                        BusEvent.ProviderWarmup(
                            sessionId = ctx.sessionId,
                            providerId = engine.providerId,
                            phase = phase,
                            epochMs = Clock.System.now().toEpochMilliseconds(),
                        ),
                    )
                },
            )
        }
        val image = result.images.firstOrNull()
            ?: error("${engine.providerId} image-gen returned zero images")

        val newAssetId = AssetId(Uuid.random().toString())
        val bundleSource = bundleBlobWriter.writeBlob(pid, newAssetId, image.pngBytes, "png")
        val newAsset = MediaAsset(
            id = newAssetId,
            source = bundleSource,
            metadata = MediaMetadata(
                duration = Duration.ZERO,
                resolution = Resolution(image.width, image.height),
                frameRate = null,
            ),
        )

        val baseInputs = JsonConfig.default.encodeToJsonElement(Input.serializer(), input).jsonObject
        val costCents = AigcPricing.estimateCents(ID, result.provenance, baseInputs)
        AigcPipeline.record(
            store = projectStore,
            projectId = pid,
            toolId = ID,
            inputHash = inputHash,
            assetId = newAssetId,
            provenance = result.provenance,
            sourceBinding = folded.appliedNodeIds.map { SourceNodeId(it) }.toSet(),
            baseInputs = baseInputs,
            costCents = costCents,
            sessionId = ctx.sessionId,
            resolvedPrompt = folded.effectivePrompt,
            originatingMessageId = ctx.messageId,
            newAsset = newAsset,
            variantIndex = ctx.variantIndex,
        )
        ctx.publishEvent(
            BusEvent.AigcCostRecorded(
                sessionId = ctx.sessionId,
                projectId = pid,
                toolId = ID,
                assetId = newAssetId.value,
                costCents = costCents,
            ),
        )

        val prov = result.provenance
        val out = Output(
            assetId = newAssetId.value,
            width = image.width,
            height = image.height,
            providerId = prov.providerId,
            modelId = prov.modelId,
            modelVersion = prov.modelVersion,
            seed = prov.seed,
            parameters = prov.parameters,
            effectivePrompt = folded.effectivePrompt,
            appliedConsistencyBindingIds = folded.appliedNodeIds,
            negativePrompt = folded.negativePrompt,
            referenceAssetIds = folded.referenceAssetIds,
            loraAdapterIds = folded.loraPins.map { it.adapterId },
            cacheHit = false,
        )
        val bindingTail = if (folded.appliedNodeIds.isEmpty()) ""
        else " [bindings: ${folded.appliedNodeIds.joinToString(", ")}]"
        return ToolResult(
            title = "generate image",
            outputForLlm = "Generated ${image.width}x${image.height} image (asset ${out.assetId}) " +
                "via ${prov.providerId}/${prov.modelId} seed=${prov.seed}$bindingTail",
            data = out,
        )
    }

    internal fun hit(
        entry: io.talevia.core.domain.lockfile.LockfileEntry,
        folded: FoldedPrompt,
        input: Input,
    ): ToolResult<Output> {
        val prov = entry.provenance
        val out = Output(
            assetId = entry.assetId.value,
            width = input.width,
            height = input.height,
            providerId = prov.providerId,
            modelId = prov.modelId,
            modelVersion = prov.modelVersion,
            seed = prov.seed,
            parameters = prov.parameters,
            effectivePrompt = folded.effectivePrompt,
            appliedConsistencyBindingIds = folded.appliedNodeIds,
            negativePrompt = folded.negativePrompt,
            referenceAssetIds = folded.referenceAssetIds,
            loraAdapterIds = folded.loraPins.map { it.adapterId },
            cacheHit = true,
        )
        return ToolResult(
            title = "generate image (cached)",
            outputForLlm = "Reused cached image ${out.assetId} (lockfile hit; seed=${prov.seed}, model=${prov.modelId})",
            data = out,
        )
    }
}
