package io.talevia.core.tool.builtin.aigc

import io.talevia.core.AssetId
import io.talevia.core.JsonConfig
import io.talevia.core.ProjectId
import io.talevia.core.SourceNodeId
import io.talevia.core.bus.BusEvent
import io.talevia.core.cost.AigcPricing
import io.talevia.core.domain.MediaAsset
import io.talevia.core.domain.MediaMetadata
import io.talevia.core.domain.ProjectStore
import io.talevia.core.domain.Resolution
import io.talevia.core.domain.source.consistency.FoldedPrompt
import io.talevia.core.permission.PermissionSpec
import io.talevia.core.platform.BundleBlobWriter
import io.talevia.core.platform.BundleMediaPathResolver
import io.talevia.core.platform.ImageGenEngine
import io.talevia.core.platform.ImageGenRequest
import io.talevia.core.tool.Tool
import io.talevia.core.tool.ToolApplicability
import io.talevia.core.tool.ToolContext
import io.talevia.core.tool.ToolResult
import kotlinx.datetime.Clock
import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonArray
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.JsonPrimitive
import kotlinx.serialization.json.buildJsonObject
import kotlinx.serialization.json.jsonObject
import kotlinx.serialization.json.put
import kotlinx.serialization.json.putJsonObject
import kotlinx.serialization.serializer
import kotlin.time.Duration
import kotlin.uuid.ExperimentalUuidApi
import kotlin.uuid.Uuid

/**
 * Generate an image via an [ImageGenEngine], persist the bytes into the project
 * bundle via a [BundleBlobWriter], append the resulting [MediaAsset] to
 * `Project.assets`, and surface a [AssetId] that downstream tools (e.g.
 * `add_clip`) can use.
 *
 * The bundle layout means generated bytes live at
 * `<bundleRoot>/media/<assetId>.png` and travel with the project — git push /
 * `cp -R` ships generated images alongside the project DAG, so collaborators
 * see the same artefacts without re-billing the provider.
 *
 * Seed + provenance handling (VISION §3.1): delegates to [AigcPipeline] so this tool
 * and every future AIGC tool share one implementation of "mint a seed if missing,
 * record the full generation parameters."
 *
 * Lockfile cache (VISION §3.1 "产物可 pin"): before calling the engine the tool
 * hashes `(tool id, effective prompt, model, seed, dimensions, bindings, negative,
 * referenceAssetIds, loraPins)` and looks the hash up in [Project.lockfile]. On a
 * hit it returns the cached asset without re-calling the provider — bit-identical
 * reuse for the common "same inputs, different turn" case. On a miss it generates,
 * persists, and appends a new entry. Every axis the engine *could* vary on must
 * be hashed, otherwise semantically distinct generations would collide on the key.
 *
 * Consistency bindings (VISION §3.3): see [AigcPipeline.foldPrompt] — identical
 * behavior to the previous implementation.
 *
 * Permission: `"aigc.generate"` — defaults to ASK via
 * [io.talevia.core.permission.DefaultPermissionRuleset]; the server maps
 * ASK to deny, which is the correct headless default.
 *
 * Project binding required: the tool resolves [Input.projectId] (or falls
 * back to [ToolContext.currentProjectId]) and writes into that bundle. A
 * dispatch with no project binding fails loud — consistent with the
 * [ToolApplicability.RequiresProjectBinding] gate.
 */
class GenerateImageTool(
    internal val engine: ImageGenEngine,
    private val bundleBlobWriter: BundleBlobWriter,
    private val projectStore: ProjectStore,
) : Tool<GenerateImageTool.Input, GenerateImageTool.Output> {

    @Serializable
    data class Input(
        val prompt: String,
        val model: String = "gpt-image-1",
        val width: Int = 1024,
        val height: Int = 1024,
        val seed: Long? = null,
        val projectId: String? = null,
        val consistencyBindingIds: List<String>? = null,
    )

    @Serializable
    data class Output(
        val assetId: String,
        val width: Int,
        val height: Int,
        val providerId: String,
        val modelId: String,
        val modelVersion: String?,
        val seed: Long,
        val parameters: JsonObject,
        val effectivePrompt: String,
        val appliedConsistencyBindingIds: List<String>,
        /** Merged negative prompt from bound style_bibles (null when no negatives were folded). */
        val negativePrompt: String? = null,
        /** Asset ids of reference images passed to the engine (empty when no character_ref supplied any). */
        val referenceAssetIds: List<String> = emptyList(),
        /** LoRA adapter ids that were pinned via bound character_refs (empty when none supplied one). */
        val loraAdapterIds: List<String> = emptyList(),
        /** True when this asset came from [Project.lockfile] rather than a fresh engine call. */
        val cacheHit: Boolean = false,
    )

    override val id: String = "generate_image"
    override val helpText: String =
        "Generate an image from a text prompt via an AIGC provider and import it as a project asset. " +
            "Bytes are persisted into the project bundle's media/ directory so the asset travels with " +
            "the project (git push / cp -R reproduces it on another machine). Records seed + model in " +
            "the project lockfile so a second call with identical inputs is a cache hit. " +
            "Pass consistencyBindingIds to reuse character / style / brand source nodes across shots."
    override val inputSerializer: KSerializer<Input> = serializer()
    override val outputSerializer: KSerializer<Output> = serializer()
    override val permission: PermissionSpec = PermissionSpec.fixed("aigc.generate")
    override val applicability: ToolApplicability = ToolApplicability.RequiresProjectBinding

    override val inputSchema: JsonObject = buildJsonObject {
        put("type", "object")
        putJsonObject("properties") {
            putJsonObject("prompt") {
                put("type", "string")
                put("description", "Text description of the image to generate.")
            }
            putJsonObject("model") {
                put("type", "string")
                put("description", "Provider-scoped model id (default: gpt-image-1).")
            }
            putJsonObject("width") {
                put("type", "integer")
                put("description", "Output image width in pixels (default: 1024).")
            }
            putJsonObject("height") {
                put("type", "integer")
                put("description", "Output image height in pixels (default: 1024).")
            }
            putJsonObject("seed") {
                put("type", "integer")
                put("description", "Optional seed for reproducibility. If omitted the tool picks one client-side so provenance is still complete. Explicit seeds make cache hits meaningful.")
            }
            putJsonObject("projectId") {
                put("type", "string")
                put("description", "Required when consistencyBindingIds is non-empty or when the project lockfile cache should be consulted.")
            }
            putJsonObject("consistencyBindingIds") {
                put("type", "array")
                put(
                    "description",
                    "Source node ids (kind core.consistency.*) to fold into the prompt. " +
                        "null (default) = auto-fold all project consistency nodes; [] = explicitly no binding; " +
                        "non-empty = fold only the listed nodes.",
                )
                putJsonObject("items") { put("type", "string") }
            }
        }
        put("required", JsonArray(listOf(JsonPrimitive("prompt"))))
        put("additionalProperties", false)
    }

    @OptIn(ExperimentalUuidApi::class)
    override suspend fun execute(input: Input, ctx: ToolContext): ToolResult<Output> {
        val pid = ctx.resolveProjectId(input.projectId)
        AigcBudgetGuard.enforce(id, projectStore, pid, ctx)
        val seed = AigcPipeline.ensureSeed(input.seed)
        val folded = resolveConsistency(input, pid)

        val referenceAssetPaths = resolveReferenceAssetPaths(pid, folded.referenceAssetIds)
        val loraKey = folded.loraPins.joinToString(",") { "${it.adapterId}@${it.weight}" }

        val inputHash = AigcPipeline.inputHash(
            listOf(
                "tool" to id,
                "model" to input.model,
                "w" to input.width.toString(),
                "h" to input.height.toString(),
                "seed" to seed.toString(),
                "prompt" to folded.effectivePrompt,
                "bindings" to folded.appliedNodeIds.joinToString(","),
                "neg" to (folded.negativePrompt ?: ""),
                "refs" to folded.referenceAssetIds.joinToString(","),
                "lora" to loraKey,
            ),
            variantIndex = ctx.variantIndex,
        )

        if (!ctx.isReplay) {
            val cached = AigcPipeline.findCached(projectStore, pid, inputHash)
            ctx.publishEvent(io.talevia.core.bus.BusEvent.AigcCacheProbe(toolId = id, hit = cached != null))
            if (cached != null) {
                return hit(cached, folded, input)
            }
        }

        val result = AigcPipeline.withProgress(
            ctx = ctx,
            jobId = "gen-image-${inputHash.take(8)}",
            startMessage = "generating ${input.width}x${input.height} image with ${input.model}",
            toolId = id,
            providerId = engine.providerId,
        ) {
            engine.generate(
                ImageGenRequest(
                    prompt = folded.effectivePrompt,
                    modelId = input.model,
                    width = input.width,
                    height = input.height,
                    seed = seed,
                    n = 1,
                    negativePrompt = folded.negativePrompt,
                    referenceAssetPaths = referenceAssetPaths,
                    loraPins = folded.loraPins,
                ),
                onWarmup = { phase ->
                    ctx.publishEvent(
                        BusEvent.ProviderWarmup(
                            sessionId = ctx.sessionId,
                            providerId = engine.providerId,
                            phase = phase,
                            epochMs = Clock.System.now().toEpochMilliseconds(),
                        ),
                    )
                },
            )
        }
        val image = result.images.firstOrNull()
            ?: error("${engine.providerId} image-gen returned zero images")

        val newAssetId = AssetId(Uuid.random().toString())
        val bundleSource = bundleBlobWriter.writeBlob(pid, newAssetId, image.pngBytes, "png")
        val newAsset = MediaAsset(
            id = newAssetId,
            source = bundleSource,
            metadata = MediaMetadata(
                duration = Duration.ZERO,
                resolution = Resolution(image.width, image.height),
                frameRate = null,
            ),
        )

        val baseInputs = JsonConfig.default.encodeToJsonElement(Input.serializer(), input).jsonObject
        val costCents = AigcPricing.estimateCents(id, result.provenance, baseInputs)
        AigcPipeline.record(
            store = projectStore,
            projectId = pid,
            toolId = id,
            inputHash = inputHash,
            assetId = newAssetId,
            provenance = result.provenance,
            sourceBinding = folded.appliedNodeIds.map { SourceNodeId(it) }.toSet(),
            baseInputs = baseInputs,
            costCents = costCents,
            sessionId = ctx.sessionId,
            resolvedPrompt = folded.effectivePrompt,
            originatingMessageId = ctx.messageId,
            newAsset = newAsset,
            variantIndex = ctx.variantIndex,
        )
        ctx.publishEvent(
            BusEvent.AigcCostRecorded(
                sessionId = ctx.sessionId,
                projectId = pid,
                toolId = id,
                assetId = newAssetId.value,
                costCents = costCents,
            ),
        )

        val prov = result.provenance
        val out = Output(
            assetId = newAssetId.value,
            width = image.width,
            height = image.height,
            providerId = prov.providerId,
            modelId = prov.modelId,
            modelVersion = prov.modelVersion,
            seed = prov.seed,
            parameters = prov.parameters,
            effectivePrompt = folded.effectivePrompt,
            appliedConsistencyBindingIds = folded.appliedNodeIds,
            negativePrompt = folded.negativePrompt,
            referenceAssetIds = folded.referenceAssetIds,
            loraAdapterIds = folded.loraPins.map { it.adapterId },
            cacheHit = false,
        )
        val bindingTail = if (folded.appliedNodeIds.isEmpty()) ""
        else " [bindings: ${folded.appliedNodeIds.joinToString(", ")}]"
        return ToolResult(
            title = "generate image",
            outputForLlm = "Generated ${image.width}x${image.height} image (asset ${out.assetId}) " +
                "via ${prov.providerId}/${prov.modelId} seed=${prov.seed}$bindingTail",
            data = out,
        )
    }

    /**
     * Native-batch path for [aigc-multi-variant-phase3-openai-native-n]
     * (cycle 33). Issues **one** provider call with `n=variantCount`
     * and writes N lockfile entries — one per variant, each with its
     * own variantIndex and inputHash — instead of the dispatcher's
     * default `runVariants(N)` loop which calls the engine N times.
     *
     * Used by [io.talevia.core.tool.builtin.aigc.dispatchImage] when
     * [engine.supportsNativeBatch] is true (currently OpenAI only) and
     * `variantCount > 1`. Engines without native batch fall back to
     * the sequential loop in [AigcGenerateToolDispatchers] — same
     * lockfile shape, more provider round-trips.
     *
     * Cache semantics: on entry, each variant's inputHash is checked
     * against the lockfile. Hits return the cached entry's Output for
     * that variant; only **misses** are forwarded to the single
     * provider call (with `n=missCount`). This handles a re-dispatch
     * partially served from cache cleanly. The provider's response is
     * a `List<GeneratedImage>` of size `missCount`; each is matched
     * to the next missing variantIndex in order. The cache-hit Output
     * is interleaved at the right index in the returned list.
     */
    @OptIn(ExperimentalUuidApi::class)
    internal suspend fun executeBatch(
        input: Input,
        ctx: ToolContext,
        variantCount: Int,
    ): List<ToolResult<Output>> {
        require(variantCount >= 1) { "executeBatch variantCount must be ≥ 1" }
        val pid = ctx.resolveProjectId(input.projectId)
        AigcBudgetGuard.enforce(id, projectStore, pid, ctx)
        val seed = AigcPipeline.ensureSeed(input.seed)
        val folded = resolveConsistency(input, pid)
        val referenceAssetPaths = resolveReferenceAssetPaths(pid, folded.referenceAssetIds)
        val loraKey = folded.loraPins.joinToString(",") { "${it.adapterId}@${it.weight}" }

        // Per-variant inputHash list — same canonical fields across
        // variants, only `variantIndex` differs.
        val perVariantHashes: List<String> = (0 until variantCount).map { i ->
            AigcPipeline.inputHash(
                listOf(
                    "tool" to id,
                    "model" to input.model,
                    "w" to input.width.toString(),
                    "h" to input.height.toString(),
                    "seed" to seed.toString(),
                    "prompt" to folded.effectivePrompt,
                    "bindings" to folded.appliedNodeIds.joinToString(","),
                    "neg" to (folded.negativePrompt ?: ""),
                    "refs" to folded.referenceAssetIds.joinToString(","),
                    "lora" to loraKey,
                ),
                variantIndex = i,
            )
        }

        // Cache probe per variant. Replay (`ctx.isReplay = true`) skips
        // every cache lookup so the provider gets called for every
        // variant — same semantic the single-variant `execute()` path
        // has when isReplay flips on.
        val cachedByIndex: Map<Int, io.talevia.core.domain.lockfile.LockfileEntry> = if (ctx.isReplay) {
            emptyMap()
        } else {
            buildMap {
                perVariantHashes.forEachIndexed { i, hash ->
                    AigcPipeline.findCached(projectStore, pid, hash)?.let { put(i, it) }
                }
            }
        }
        // Surface cache-probe events for each variant before potentially
        // calling the provider so observers see the per-variant
        // hit/miss split.
        cachedByIndex.keys.forEach {
            ctx.publishEvent(io.talevia.core.bus.BusEvent.AigcCacheProbe(toolId = id, hit = true))
        }
        val missingIndices = (0 until variantCount).filter { it !in cachedByIndex }
        missingIndices.forEach {
            ctx.publishEvent(io.talevia.core.bus.BusEvent.AigcCacheProbe(toolId = id, hit = false))
        }

        // Provider call — only when there's at least one cache miss.
        val freshImages: List<io.talevia.core.platform.GeneratedImage> = if (missingIndices.isEmpty()) {
            emptyList()
        } else {
            val result = AigcPipeline.withProgress(
                ctx = ctx,
                jobId = "gen-image-batch-${perVariantHashes.first().take(8)}-n${missingIndices.size}",
                startMessage = "generating ${input.width}x${input.height} image batch ×${missingIndices.size} with ${input.model}",
                toolId = id,
                providerId = engine.providerId,
            ) {
                engine.generate(
                    ImageGenRequest(
                        prompt = folded.effectivePrompt,
                        modelId = input.model,
                        width = input.width,
                        height = input.height,
                        seed = seed,
                        n = missingIndices.size,
                        negativePrompt = folded.negativePrompt,
                        referenceAssetPaths = referenceAssetPaths,
                        loraPins = folded.loraPins,
                    ),
                    onWarmup = { phase ->
                        ctx.publishEvent(
                            BusEvent.ProviderWarmup(
                                sessionId = ctx.sessionId,
                                providerId = engine.providerId,
                                phase = phase,
                                epochMs = Clock.System.now().toEpochMilliseconds(),
                            ),
                        )
                    },
                )
            }
            check(result.images.size == missingIndices.size) {
                "${engine.providerId} returned ${result.images.size} images for n=${missingIndices.size} batch — " +
                    "engine claimed supportsNativeBatch but didn't honour the contract"
            }
            // Stash provenance for downstream record() calls.
            cachedProvenance = result.provenance
            result.images
        }

        val baseInputs = JsonConfig.default.encodeToJsonElement(Input.serializer(), input).jsonObject
        val results = MutableList<ToolResult<Output>?>(variantCount) { null }

        // Pair fresh images with their corresponding miss indices in order.
        var imageCursor = 0
        for (i in 0 until variantCount) {
            val cached = cachedByIndex[i]
            if (cached != null) {
                results[i] = hit(cached, folded, input)
                continue
            }
            val image = freshImages[imageCursor++]
            val newAssetId = AssetId(Uuid.random().toString())
            val bundleSource = bundleBlobWriter.writeBlob(pid, newAssetId, image.pngBytes, "png")
            val newAsset = MediaAsset(
                id = newAssetId,
                source = bundleSource,
                metadata = MediaMetadata(
                    duration = Duration.ZERO,
                    resolution = Resolution(image.width, image.height),
                    frameRate = null,
                ),
            )
            val variantHash = perVariantHashes[i]
            val provenance = cachedProvenance ?: error("provenance must be set when there's at least one fresh image")
            val costCents = AigcPricing.estimateCents(id, provenance, baseInputs)
            AigcPipeline.record(
                store = projectStore,
                projectId = pid,
                toolId = id,
                inputHash = variantHash,
                assetId = newAssetId,
                provenance = provenance,
                sourceBinding = folded.appliedNodeIds.map { SourceNodeId(it) }.toSet(),
                baseInputs = baseInputs,
                costCents = costCents,
                sessionId = ctx.sessionId,
                resolvedPrompt = folded.effectivePrompt,
                originatingMessageId = ctx.messageId,
                newAsset = newAsset,
                variantIndex = i,
            )
            ctx.publishEvent(
                BusEvent.AigcCostRecorded(
                    sessionId = ctx.sessionId,
                    projectId = pid,
                    toolId = id,
                    assetId = newAssetId.value,
                    costCents = costCents,
                ),
            )
            val out = Output(
                assetId = newAssetId.value,
                width = image.width,
                height = image.height,
                providerId = provenance.providerId,
                modelId = provenance.modelId,
                modelVersion = provenance.modelVersion,
                seed = provenance.seed,
                parameters = provenance.parameters,
                effectivePrompt = folded.effectivePrompt,
                appliedConsistencyBindingIds = folded.appliedNodeIds,
                negativePrompt = folded.negativePrompt,
                referenceAssetIds = folded.referenceAssetIds,
                loraAdapterIds = folded.loraPins.map { it.adapterId },
                cacheHit = false,
            )
            val bindingTail = if (folded.appliedNodeIds.isEmpty()) ""
            else " [bindings: ${folded.appliedNodeIds.joinToString(", ")}]"
            results[i] = ToolResult(
                title = "generate image (batch v$i)",
                outputForLlm = "Generated ${image.width}x${image.height} image (asset ${out.assetId}, variant $i) " +
                    "via ${provenance.providerId}/${provenance.modelId} seed=${provenance.seed}$bindingTail",
                data = out,
            )
        }
        cachedProvenance = null
        @Suppress("UNCHECKED_CAST")
        return results.toList() as List<ToolResult<Output>>
    }

    /** Local stash so [executeBatch] can pass the single-call provenance into the per-variant record() calls. */
    private var cachedProvenance: io.talevia.core.platform.GenerationProvenance? = null

    private fun hit(
        entry: io.talevia.core.domain.lockfile.LockfileEntry,
        folded: FoldedPrompt,
        input: Input,
    ): ToolResult<Output> {
        val prov = entry.provenance
        val out = Output(
            assetId = entry.assetId.value,
            width = input.width,
            height = input.height,
            providerId = prov.providerId,
            modelId = prov.modelId,
            modelVersion = prov.modelVersion,
            seed = prov.seed,
            parameters = prov.parameters,
            effectivePrompt = folded.effectivePrompt,
            appliedConsistencyBindingIds = folded.appliedNodeIds,
            negativePrompt = folded.negativePrompt,
            referenceAssetIds = folded.referenceAssetIds,
            loraAdapterIds = folded.loraPins.map { it.adapterId },
            cacheHit = true,
        )
        return ToolResult(
            title = "generate image (cached)",
            outputForLlm = "Reused cached image ${out.assetId} (lockfile hit; seed=${prov.seed}, model=${prov.modelId})",
            data = out,
        )
    }

    private suspend fun resolveReferenceAssetPaths(
        pid: ProjectId,
        assetIds: List<String>,
    ): List<String> {
        if (assetIds.isEmpty()) return emptyList()
        val project = projectStore.get(pid)
            ?: error("project ${pid.value} not found when resolving reference assets")
        val bundleRoot = projectStore.pathOf(pid)
            ?: error(
                "project ${pid.value} has no registered bundle path; reference asset resolution " +
                    "requires a file-backed ProjectStore — open or create the bundle first.",
            )
        val resolver = BundleMediaPathResolver(project, bundleRoot)
        return assetIds.map { resolver.resolve(AssetId(it)) }
    }

    private suspend fun resolveConsistency(input: Input, pid: ProjectId): FoldedPrompt {
        val bindingIds = input.consistencyBindingIds
        if (bindingIds != null && bindingIds.isEmpty()) {
            return io.talevia.core.domain.source.consistency
                .foldConsistencyIntoPrompt(input.prompt, emptyList())
        }
        val project = projectStore.get(pid)
            ?: error("Project ${pid.value} not found when resolving consistency bindings")
        return AigcPipeline.foldPrompt(
            project = project,
            basePrompt = input.prompt,
            bindingIds = bindingIds?.map { SourceNodeId(it) },
        )
    }
}
