package io.talevia.core.platform

import io.talevia.core.AssetId
import io.talevia.core.ProjectId
import io.talevia.core.domain.MediaSource
import io.talevia.core.domain.Project
import io.talevia.core.domain.ProjectStore
import io.talevia.core.domain.ProjectSummary
import kotlinx.coroutines.test.runTest
import okio.Buffer
import okio.Path
import okio.Path.Companion.toPath
import okio.fakefilesystem.FakeFileSystem
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertFailsWith
import kotlin.test.assertTrue

/**
 * Direct tests for [FileBundleBlobWriter] —
 * `core/platform/BundleBlobWriter.kt`. The Okio-backed
 * AIGC-blob persister that lands generated bytes inside
 * the project bundle's `media/` directory so `git push`
 * carries them to collaborators. Cycle 159 audit: 127 LOC,
 * 0 transitive test refs.
 *
 * Three correctness contracts pinned:
 *
 * 1. **Unregistered project → throws with diagnostic.** A
 *    caller that forgot to open/create the bundle first
 *    gets a loud error naming the offending projectId, NOT
 *    a silent write to a default location. The kdoc-
 *    documented "open or create the bundle first" guidance
 *    surfaces in the error message.
 *
 * 2. **`format` extension is `.`-trimmed; blank → `"bin"`.**
 *    Callers can pass either `"png"` or `".png"` and get
 *    the same result. A blank/empty format defaults to
 *    `"bin"` so the file always has SOME extension.
 *
 * 3. **Atomic write via tmpfile + atomicMove.** A crashed
 *    write never leaves a half-written `media/<id>.<ext>`
 *    behind. The tmpfile pattern is the same approach
 *    `FileProjectStore`'s envelope writes use.
 *
 * Plus the streaming-vs-bytes semantic split (writeBlob
 * via writeBlobStreaming for the prod impl).
 */
class BundleBlobWriterTest {

    private val bundleRoot: Path = "/bundle".toPath()

    /** Minimal ProjectStore — only `pathOf(id)` is exercised. */
    private class FakeProjectStore(
        private val paths: Map<ProjectId, Path> = emptyMap(),
    ) : ProjectStore {
        override suspend fun get(id: ProjectId): Project? = null
        override suspend fun upsert(title: String, project: Project) = error("not used")
        override suspend fun list(): List<Project> = emptyList()
        override suspend fun delete(id: ProjectId, deleteFiles: Boolean) = error("not used")
        override suspend fun setTitle(id: ProjectId, title: String) = error("not used")
        override suspend fun summary(id: ProjectId): ProjectSummary? = null
        override suspend fun listSummaries(): List<ProjectSummary> = emptyList()
        override suspend fun mutate(id: ProjectId, block: suspend (Project) -> Project): Project = error("not used")
        override suspend fun pathOf(id: ProjectId): Path? = paths[id]
    }

    private fun fakeFs(): FakeFileSystem {
        val fs = FakeFileSystem()
        fs.createDirectories(bundleRoot)
        return fs
    }

    private fun storeWith(pid: ProjectId): FakeProjectStore =
        FakeProjectStore(mapOf(pid to bundleRoot))

    // ── unregistered project → throw ────────────────────────────

    @Test fun unregisteredProjectThrowsWithDiagnostic() = runTest {
        val fs = fakeFs()
        val store = FakeProjectStore() // empty — no projects registered
        val writer = FileBundleBlobWriter(store, fs)

        val ex = assertFailsWith<IllegalStateException> {
            writer.writeBlob(
                projectId = ProjectId("ghost"),
                assetId = AssetId("a"),
                bytes = byteArrayOf(1, 2, 3),
                format = "png",
            )
        }
        val msg = ex.message.orEmpty()
        assertTrue("ghost" in msg, "project id surfaces; got: $msg")
        assertTrue(
            "open or create" in msg,
            "kdoc-documented guidance phrasing; got: $msg",
        )
    }

    // ── happy path: writes to media/<assetId>.<ext> ─────────────

    @Test fun writeBlobLandsAtMediaSlashAssetIdDotFormat() = runTest {
        val fs = fakeFs()
        val pid = ProjectId("p")
        val writer = FileBundleBlobWriter(storeWith(pid), fs)

        val result = writer.writeBlob(
            projectId = pid,
            assetId = AssetId("clip-7"),
            bytes = "hello".encodeToByteArray(),
            format = "png",
        )

        // Pin: returned MediaSource.BundleFile has the
        // canonical `media/<assetId>.<ext>` shape.
        assertEquals(MediaSource.BundleFile("media/clip-7.png"), result)
        // Pin: file exists at the expected absolute path
        // inside the bundle.
        val target = bundleRoot.resolve("media/clip-7.png")
        assertTrue(fs.exists(target), "file persisted")
        // Pin: file content matches input bytes.
        val readBack = fs.read(target) { readUtf8() }
        assertEquals("hello", readBack, "bytes round-trip")
    }

    // ── format normalization ────────────────────────────────────

    @Test fun formatLeadingDotIsTrimmed() = runTest {
        // Pin: caller passes ".png" or "png" — both produce
        // the same `media/<id>.png` filename. Drift to
        // literal-format-string would silently produce
        // `media/<id>..png` (double dot).
        val fs = fakeFs()
        val pid = ProjectId("p")
        val writer = FileBundleBlobWriter(storeWith(pid), fs)

        val result = writer.writeBlob(
            projectId = pid,
            assetId = AssetId("a"),
            bytes = byteArrayOf(),
            format = ".jpg",
        )
        assertEquals(MediaSource.BundleFile("media/a.jpg"), result)
        assertTrue(fs.exists(bundleRoot.resolve("media/a.jpg")))
    }

    @Test fun blankFormatDefaultsToBin() = runTest {
        // Pin: empty / whitespace-only format → "bin"
        // extension. Drift to "" extension would produce
        // `media/<id>.` (trailing dot — invalid path on
        // some filesystems).
        val fs = fakeFs()
        val pid = ProjectId("p")
        val writer = FileBundleBlobWriter(storeWith(pid), fs)

        val result1 = writer.writeBlob(pid, AssetId("a1"), byteArrayOf(), format = "")
        assertEquals(MediaSource.BundleFile("media/a1.bin"), result1)

        val result2 = writer.writeBlob(pid, AssetId("a2"), byteArrayOf(), format = ".")
        // ".".trimStart('.') → "" → ifBlank { "bin" } → "bin"
        assertEquals(MediaSource.BundleFile("media/a2.bin"), result2)
    }

    @Test fun multipleLeadingDotsAreAllTrimmed() {
        // Pin: trimStart('.') strips ALL leading dots, not just
        // one. Drift to removePrefix(".") would only strip
        // the first.
        runTest {
            val fs = fakeFs()
            val pid = ProjectId("p")
            val writer = FileBundleBlobWriter(storeWith(pid), fs)
            val result = writer.writeBlob(pid, AssetId("a"), byteArrayOf(), format = "...mp4")
            // "...mp4".trimStart('.') → "mp4"
            assertEquals(MediaSource.BundleFile("media/a.mp4"), result)
        }
    }

    // ── streaming entry point ───────────────────────────────────

    @Test fun writeBlobStreamingProducesIdenticalResultToWriteBlob() = runTest {
        // Pin: production impl overrides writeBlobStreaming
        // to stream directly. Both entry points should
        // produce the same on-disk file + same return value
        // for identical input bytes.
        val fs = fakeFs()
        val pid = ProjectId("p")
        val writer = FileBundleBlobWriter(storeWith(pid), fs)
        val payload = "streamed".encodeToByteArray()

        val byBlob = writer.writeBlob(pid, AssetId("a-blob"), payload, "txt")
        val source = Buffer().apply { write(payload) }
        val byStream = writer.writeBlobStreaming(pid, AssetId("a-stream"), source, "txt")

        // Different assetIds → different paths, same shape.
        assertEquals(MediaSource.BundleFile("media/a-blob.txt"), byBlob)
        assertEquals(MediaSource.BundleFile("media/a-stream.txt"), byStream)
        // Same content.
        val blobBytes = fs.read(bundleRoot.resolve("media/a-blob.txt")) { readByteArray() }
        val streamBytes = fs.read(bundleRoot.resolve("media/a-stream.txt")) { readByteArray() }
        assertEquals(blobBytes.toList(), streamBytes.toList())
    }

    // ── atomic write (tmpfile cleanup) ──────────────────────────

    @Test fun atomicMoveResultsInNoLingeringTmpFiles() = runTest {
        // Pin: write is atomic — tmp file is moved into place,
        // not left behind. Inspecting the bundle's media dir
        // post-write should show ONLY the target file, no
        // *.tmp.* siblings.
        val fs = fakeFs()
        val pid = ProjectId("p")
        val writer = FileBundleBlobWriter(storeWith(pid), fs)
        writer.writeBlob(pid, AssetId("a"), byteArrayOf(7, 7, 7), "bin")

        val mediaDir = bundleRoot.resolve("media")
        val files = fs.list(mediaDir)
        assertEquals(1, files.size, "only target file; got: $files")
        assertEquals("a.bin", files.single().name)
    }

    @Test fun mediaDirectoryIsCreatedOnFirstWriteIfAbsent() = runTest {
        // Pin: `fs.createDirectories(mediaDir)` is called
        // before sink open. A fresh bundle that has never
        // written media still gets the dir materialised.
        // Drift to "assert dir exists" would crash the very
        // first AIGC dispatch against a freshly-created
        // bundle.
        val fs = FakeFileSystem()
        // Plant only the bundle root, NOT the media subdir.
        fs.createDirectories(bundleRoot)
        val pid = ProjectId("p")
        val writer = FileBundleBlobWriter(storeWith(pid), fs)

        writer.writeBlob(pid, AssetId("a"), byteArrayOf(), "png")

        assertTrue(
            fs.exists(bundleRoot.resolve("media")),
            "media/ created on demand",
        )
    }

    // ── multiple writes accumulate ──────────────────────────────

    @Test fun multipleWritesProduceMultipleFiles() = runTest {
        val fs = fakeFs()
        val pid = ProjectId("p")
        val writer = FileBundleBlobWriter(storeWith(pid), fs)
        writer.writeBlob(pid, AssetId("a1"), "one".encodeToByteArray(), "txt")
        writer.writeBlob(pid, AssetId("a2"), "two".encodeToByteArray(), "txt")
        writer.writeBlob(pid, AssetId("a3"), "three".encodeToByteArray(), "txt")

        val mediaDir = bundleRoot.resolve("media")
        val names = fs.list(mediaDir).map { it.name }.toSet()
        assertEquals(setOf("a1.txt", "a2.txt", "a3.txt"), names)
    }

    @Test fun writeBlobOverwritesExistingFileWithSameAssetId() = runTest {
        // Pin: same assetId + format → file overwritten
        // (atomicMove replaces target). Drift to "throw on
        // exists" would break re-runs of identical AIGC
        // calls.
        val fs = fakeFs()
        val pid = ProjectId("p")
        val writer = FileBundleBlobWriter(storeWith(pid), fs)
        writer.writeBlob(pid, AssetId("a"), "first".encodeToByteArray(), "txt")
        writer.writeBlob(pid, AssetId("a"), "second".encodeToByteArray(), "txt")

        val readBack = fs.read(bundleRoot.resolve("media/a.txt")) { readUtf8() }
        assertEquals("second", readBack, "second write overwrites first")
    }

    // ── default-impl writeBlobStreaming via interface ───────────

    @Test fun defaultStreamingImplMaterialisesBytesAndDelegatesToWriteBlob() = runTest {
        // Pin: the BundleBlobWriter interface's DEFAULT
        // writeBlobStreaming reads the source into bytes and
        // calls writeBlob. Test fakes that only override
        // writeBlob get streaming "for free" — at the cost of
        // memory materialisation per kdoc.
        val recordedCalls = mutableListOf<Triple<ProjectId, AssetId, ByteArray>>()
        val fakeWriter = object : BundleBlobWriter {
            override suspend fun writeBlob(
                projectId: ProjectId,
                assetId: AssetId,
                bytes: ByteArray,
                format: String,
            ): MediaSource.BundleFile {
                recordedCalls += Triple(projectId, assetId, bytes)
                return MediaSource.BundleFile("media/${assetId.value}.$format")
            }
        }
        val source = Buffer().apply { write("streamed-payload".encodeToByteArray()) }
        val result = fakeWriter.writeBlobStreaming(
            projectId = ProjectId("p"),
            assetId = AssetId("a"),
            source = source,
            format = "bin",
        )

        // Pin: default streaming impl delegated to writeBlob
        // exactly once.
        assertEquals(1, recordedCalls.size, "exactly one writeBlob call")
        val (pid, aid, bytes) = recordedCalls.single()
        assertEquals(ProjectId("p"), pid)
        assertEquals(AssetId("a"), aid)
        assertEquals("streamed-payload", bytes.decodeToString())
        assertEquals(MediaSource.BundleFile("media/a.bin"), result)
    }
}
